In [15]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array( object= list_)

print(type(list_))        # Output: <class 'list'>
print(type(array_list))  # Output: <class 'numpy.ndarray'>
# The variable list_ is a Python list of strings, while the variable array_list is a NumPy array of strings.

<class 'list'>
<class 'numpy.ndarray'>


In [17]:
# import numpy as np
# list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
# array_list = np.array(object = list_)

# Q2. Write a code to print the data type of each and every element of both the variables list_ and
# arra_list.

In [18]:
import numpy as np

In [20]:

list_ = ['1', '2', '3', '4', '5']
for ele in list_:
    print(type(ele))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [37]:
array_list = np.array(object=list_)

In [38]:
type(array_list)

numpy.ndarray

In [22]:
for element in array_list:
    print(type(element))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [23]:
# Q3. Considering the following changes in the variable, array_list:
# array_list = np.array(object = list_, dtype = int)

In [32]:
# array_list = np.array(object = list_, dtype = int)

In [33]:
print(type(array_list))

<class 'numpy.ndarray'>


In [34]:
array_list = np.array(object = list_)

In [35]:
print(type(array_list))

<class 'numpy.ndarray'>


In [39]:
type(list_)

list

In [40]:
# No differnce

In [41]:
# Consider the below code to answer further questions:
# import numpy as np
# num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
# num_array = np.array(object = num_list)
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

In [42]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [43]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
np.shape(num_array)

(2, 3)

In [48]:
np.size(num_array)

6

In [49]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
# creation function.
# [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [52]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [53]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?
# [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [54]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
# pip install openai
import os
import openai

openai.api_key = os.getenv("OPENAI_API_KEY")

response = openai.Completion.create(
  model="text-davinci-003",
  prompt="Correct this to standard English:\n\nShe no went to the market.\n\nShe did not go to the market.",
  temperature=0,
  max_tokens=60,
  top_p=1,
  frequency_penalty=0,
  presence_penalty=0
)

ModuleNotFoundError: No module named 'openai'